apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mediawiki-139
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/mediawiki
    repoURL: https://github.com/wbstack/charts
    targetRevision: HEAD
    helm:
      valuesObject:
{{ tpl (.Files.Get "env/production/mediawiki-139.values.yaml.gotmpl") . | indent 8 }}
{{ tpl (.Files.Get "env/local/mediawiki-139.values.yaml.gotmpl") . | indent 8 }}
  syncPolicy:
    automated:
      selfHeal: true